[package]
name = "pathtracer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bvh = "0.7.1"
glam = "0.22.0"
image = "0.24.5"
rand = "0.8.5"
tobj = "3.2.4"
